# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Alex Sutii
tagline:          'A Jekyll theme'
description:      '<a href="https://github.com/sutiialex">Software engineer</a>, <a href="https://www.facebook.com/ChiliConComedy/">Improv player</a>'

author:
  name:           'Alexandru Sutii'
  url:            https://www.linkedin.com/in/alexandru-sutii-778a3b32/

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sutiialex/sutiialex.github.io

plugins:
    - jekyll-paginate
paginate: 1
